import type { Command } from 'commander';
import pc from 'picocolors';
import { getCurrentPRNumber, fetchPR, assignReviewers, postComment } from '../utils/github.js';
import { fetchGitLog, scoreContributors } from '../algorithms/expertise.js';
import { fetchReviewerLoads, buildRecommendations } from '../algorithms/loadbalancer.js';
import { groupFilesBySemantics, generateSummary, detectBreakingChanges } from '../algorithms/semantic.js';
import { loadConfig } from '../utils/config.js';
import type { FileCluster } from '../types/index.js';

function clusterIcon(type: string): string {
  const icons: Record<string, string> = {
    test: '🧪', config: '⚙️', auth: '🔐', api: '🔌',
    ui: '🎨', docs: '📝', deps: '📦', ci: '🤖', core: '⚡', other: '📁',
  };
  return icons[type] ?? '📁';
}

function buildMarkdownSummary(clusters: FileCluster[], breaking: string[], prTitle: string): string {
  let md = `## 🤖 PR Summary — *${prTitle}*\n\n`;
  md += `> Generated by [pr-accelerator](https://github.com/phoenix-assistant/pr-accelerator)\n\n`;

  for (const cluster of clusters) {
    md += `### ${clusterIcon(cluster.type)} ${cluster.label}\n`;
    md += `**+${cluster.additions} -${cluster.deletions}** across ${cluster.files.length} file(s)\n\n`;
    for (const f of cluster.files.slice(0, 6)) {
      md += `- \`${f}\`\n`;
    }
    if (cluster.files.length > 6) md += `- *...and ${cluster.files.length - 6} more*\n`;
    md += '\n';
  }

  if (breaking.length > 0) {
    md += `### ⚠️ Potential Breaking Changes\n\n`;
    for (const w of breaking) md += `- ${w}\n`;
    md += '\n';
  }

  return md;
}

export function registerCICommand(program: Command): void {
  const ci = program
    .command('ci')
    .description('CI mode commands (for use in GitHub Actions)');

  ci
    .command('auto-assign')
    .description('Auto-assign reviewers to the current PR')
    .option('-r, --repo <repo>', 'GitHub repo (owner/repo)')
    .action(async (opts: { repo?: string }) => {
      const prNumber = getCurrentPRNumber();
      if (!prNumber) {
        console.error(pc.red('Could not determine PR number. Set GITHUB_PR_NUMBER env var or run from a PR branch.'));
        process.exit(1);
      }

      const config = loadConfig();
      console.log(pc.dim(`Fetching PR #${prNumber}...`));

      let pr;
      try {
        pr = fetchPR(prNumber, opts.repo);
      } catch (err) {
        console.error(pc.red(`Failed to fetch PR: ${(err as Error).message}`));
        process.exit(1);
      }

      // Skip draft PRs
      if (pr.draft) {
        console.log(pc.yellow('Skipping draft PR.'));
        return;
      }

      const entries = fetchGitLog({ decayDays: config.expertiseDecayDays });
      const prFilePaths = pr.files.map((f) => f.path);
      const expertiseScores = scoreContributors(prFilePaths, entries, config.expertiseDecayDays, pr.author);

      if (expertiseScores.length === 0) {
        console.log(pc.yellow('No reviewers found in git history.'));
        return;
      }

      const topReviewers = expertiseScores.slice(0, 6).map((e) => e.contributor);
      const loads = fetchReviewerLoads(topReviewers, { repo: opts.repo });
      const recs = buildRecommendations(expertiseScores, loads, config.minReviewers);

      const reviewers = recs.map((r) => r.reviewer);
      console.log(pc.dim(`Assigning reviewers: ${reviewers.join(', ')}`));

      try {
        assignReviewers(prNumber, reviewers, opts.repo);
        console.log(pc.green(`✓ Assigned ${reviewers.join(', ')} to PR #${prNumber}`));
      } catch (err) {
        console.error(pc.red(`Failed to assign reviewers: ${(err as Error).message}`));
        process.exit(1);
      }
    });

  ci
    .command('summarize')
    .description('Auto-post a semantic summary as a PR comment')
    .option('-r, --repo <repo>', 'GitHub repo (owner/repo)')
    .action(async (opts: { repo?: string }) => {
      const prNumber = getCurrentPRNumber();
      if (!prNumber) {
        console.error(pc.red('Could not determine PR number.'));
        process.exit(1);
      }

      console.log(pc.dim(`Fetching PR #${prNumber}...`));

      let pr;
      try {
        pr = fetchPR(prNumber, opts.repo);
      } catch (err) {
        console.error(pc.red(`Failed to fetch PR: ${(err as Error).message}`));
        process.exit(1);
      }

      const clusters = groupFilesBySemantics(pr.files);
      const breaking = detectBreakingChanges(pr.files);
      const md = buildMarkdownSummary(clusters, breaking, pr.title);

      try {
        postComment(prNumber, md, opts.repo);
        console.log(pc.green(`✓ Posted semantic summary to PR #${prNumber}`));
      } catch (err) {
        console.error(pc.red(`Failed to post comment: ${(err as Error).message}`));
        process.exit(1);
      }
    });
}
