import type { Command } from 'commander';
import pc from 'picocolors';
import { fetchPR, postComment } from '../utils/github.js';
import { groupFilesBySemantics, generateSummary, detectBreakingChanges } from '../algorithms/semantic.js';
import { printClusters, printSection } from '../utils/output.js';
import type { FileCluster } from '../types/index.js';

interface SummarizeOptions {
  repo?: string;
  comment?: boolean;
  markdown?: boolean;
}

function clustersToMarkdown(clusters: FileCluster[], breaking: string[], prTitle: string): string {
  let md = `## 🤖 PR Summary — *${prTitle}*\n\n`;
  md += `> Generated by [pr-accelerator](https://github.com/phoenix-assistant/pr-accelerator)\n\n`;

  for (const cluster of clusters) {
    const icon = clusterIcon(cluster.type);
    md += `### ${icon} ${cluster.label}\n`;
    md += `**${cluster.additions} additions, ${cluster.deletions} deletions** across ${cluster.files.length} file(s)\n\n`;
    for (const f of cluster.files.slice(0, 8)) {
      md += `- \`${f}\`\n`;
    }
    if (cluster.files.length > 8) {
      md += `- *...and ${cluster.files.length - 8} more*\n`;
    }
    md += '\n';
  }

  if (breaking.length > 0) {
    md += `### ⚠️ Potential Breaking Changes\n\n`;
    for (const w of breaking) {
      md += `- ${w}\n`;
    }
    md += '\n';
  }

  return md;
}

function clusterIcon(type: string): string {
  const icons: Record<string, string> = {
    test: '🧪', config: '⚙️', auth: '🔐', api: '🔌',
    ui: '🎨', docs: '📝', deps: '📦', ci: '🤖', core: '⚡', other: '📁',
  };
  return icons[type] ?? '📁';
}

export function registerSummarizeCommand(program: Command): void {
  program
    .command('summarize <pr-number>')
    .description('Generate a semantic diff summary for a PR')
    .option('-r, --repo <repo>', 'GitHub repo (owner/repo)')
    .option('--comment', 'Post the summary as a PR comment')
    .option('--markdown', 'Output as markdown instead of terminal format')
    .action(async (prNumber: string, opts: SummarizeOptions) => {
      const n = parseInt(prNumber, 10);
      if (isNaN(n)) {
        console.error(pc.red('Invalid PR number'));
        process.exit(1);
      }

      console.log(pc.dim(`Fetching PR #${n}...`));

      let pr;
      try {
        pr = fetchPR(n, opts.repo);
      } catch (err: unknown) {
        console.error(pc.red(`Failed to fetch PR: ${(err as Error).message}`));
        process.exit(1);
      }

      const clusters = groupFilesBySemantics(pr.files);
      const breaking = detectBreakingChanges(pr.files);

      if (opts.markdown || opts.comment) {
        const md = clustersToMarkdown(clusters, breaking, pr.title);
        if (opts.comment) {
          console.log(pc.dim('Posting comment...'));
          try {
            postComment(n, md, opts.repo);
            console.log(pc.green(`✓ Comment posted to PR #${n}`));
          } catch (err: unknown) {
            console.error(pc.red(`Failed to post comment: ${(err as Error).message}`));
            process.exit(1);
          }
        } else {
          console.log(md);
        }
      } else {
        printClusters(clusters);
        if (breaking.length > 0) {
          printSection('⚠️  Potential Breaking Changes');
          for (const w of breaking) {
            console.log(`  ${pc.yellow('•')} ${w}`);
          }
        }
        const summary = generateSummary(clusters, pr.title);
        printSection('One-liner Summary');
        console.log(`  ${pc.italic(summary)}\n`);
      }
    });
}
